set language british;
/*CREATE A TEMP TABLE THEN INSERT IT INTO THE PERMENTANT TABLE*/
/*CREATE TABLE lfliveextract_session (*/
DECLARE @Temp_Table TABLE(
[sessionid] BIGINT,
[starttime] DATETIME,
[endtime] DATETIME,
[lastactiontime] DATETIME,
[technicianname] NVARCHAR(255),
[technicianid] INT,
[sessiontype] NVARCHAR(50),
[status] NVARCHAR(50),
[contactname] NVARCHAR(255),
[companyname] NVARCHAR(255),
[email] NVARCHAR(255),
[subject] NVARCHAR(255),
[existingticketno] NVARCHAR(255),
[santander] BIT,
[trackingid] NVARCHAR(255),
[customerip] NVARCHAR(15),
[deviceid] NVARCHAR(255),
[toolsused] NVARCHAR(50),
[channelid] INT,
[channelname] NVARCHAR(255),
[callingcard] NVARCHAR(255),
[connectingtime] INT,
[waitingtime] INT,
[totaltime] INT,
[activetime] INT,
[worktime] INT,
[holdtime] INT,
[transfertime] INT,
[rebootingtime] INT,
[reconnectingtime] INT,
[platform] NVARCHAR(50),
[technicianemail] NVARCHAR(255),
[techniciangroup] NVARCHAR(255),
[browsertype] NVARCHAR(50)
);
INSERT INTO @Temp_Table
SELECT 
CONVERT(BIGINT,[sessionid]),
CASE WHEN [starttime] = '' THEN NULL ELSE CONVERT(DATETIME,[starttime]) END AS [starttime],
CASE WHEN [endtime] = '' THEN NULL ELSE CONVERT(DATETIME,[endtime]) END AS [endtime],
CASE WHEN lastactiontime = '' THEN NULL ELSE CONVERT(DATETIME,[lastactiontime]) END AS lastactiontime,
[technicianname],
CONVERT(INT,[technicianid]),
[sessiontype],
[status],
[contactname],
[companyname],
[email],
[subject],
CASE WHEN [existingticketno] = '' THEN NULL ELSE [existingticketno] END AS [existingticketno],
CONVERT(BIT,[santander]),
[trackingid],
[customerip],
[deviceid],
[toolsused],
CONVERT(INT,[channelid]),
[channelname],
[callingcard],
CONVERT(INT,[connectingtime]),
CONVERT(INT,[waitingtime]),
CONVERT(INT,[totaltime]),
CONVERT(INT,[activetime]),
CONVERT(INT,[worktime]),
CONVERT(INT,[holdtime]),
CONVERT(INT,[transfertime]),
CONVERT(INT,[rebootingtime]),
CONVERT(INT,[reconnectingtime]),
[platform],
[technicianemail],
[techniciangroup],
[browsertype]
FROM 
[dbo].[stg] stg;

/*MERGE THE TEMP TABLE WITH THE CLOSED INCIDENTS TABLE*/
MERGE [dbo].[lfliveextract_session] target
Using @Temp_Table source
ON (
TARGET.[sessionid] = SOURCE.[sessionid] AND
TARGET.[starttime] = SOURCE.[starttime]
)
WHEN MATCHED
THEN UPDATE
SET
TARGET.[sessionid] = SOURCE.[sessionid],
TARGET.[starttime] = SOURCE.[starttime],
TARGET.[endtime] = SOURCE.[endtime],
TARGET.[lastactiontime] = SOURCE.[lastactiontime],
TARGET.[technicianname] = SOURCE.[technicianname],
TARGET.[technicianid] = SOURCE.[technicianid],
TARGET.[sessiontype] = SOURCE.[sessiontype],
TARGET.[status] = SOURCE.[status],
TARGET.[contactname] = SOURCE.[contactname],
TARGET.[companyname] = SOURCE.[companyname],
TARGET.[email] = SOURCE.[email],
TARGET.[subject] = SOURCE.[subject],
TARGET.[existingticketno] = SOURCE.[existingticketno],
TARGET.[santander] = SOURCE.[santander],
TARGET.[trackingid] = SOURCE.[trackingid],
TARGET.[customerip] = SOURCE.[customerip],
TARGET.[deviceid] = SOURCE.[deviceid],
TARGET.[toolsused] = SOURCE.[toolsused],
TARGET.[channelid] = SOURCE.[channelid],
TARGET.[channelname] = SOURCE.[channelname],
TARGET.[callingcard] = SOURCE.[callingcard],
TARGET.[connectingtime] = SOURCE.[connectingtime],
TARGET.[waitingtime] = SOURCE.[waitingtime],
TARGET.[totaltime] = SOURCE.[totaltime],
TARGET.[activetime] = SOURCE.[activetime],
TARGET.[worktime] = SOURCE.[worktime],
TARGET.[holdtime] = SOURCE.[holdtime],
TARGET.[transfertime] = SOURCE.[transfertime],
TARGET.[rebootingtime] = SOURCE.[rebootingtime],
TARGET.[reconnectingtime] = SOURCE.[reconnectingtime],
TARGET.[platform] = SOURCE.[platform],
TARGET.[technicianemail] = SOURCE.[technicianemail],
TARGET.[techniciangroup] = SOURCE.[techniciangroup],
TARGET.[browsertype] = SOURCE.[browsertype]
WHEN NOT MATCHED BY TARGET
THEN INSERT 
(
[sessionid],
[starttime],
[endtime],
[lastactiontime],
[technicianname],
[technicianid],
[sessiontype],
[status],
[contactname],
[companyname],
[email],
[subject],
[existingticketno],
[santander],
[trackingid],
[customerip],
[deviceid],
[toolsused],
[channelid],
[channelname],
[callingcard],
[connectingtime],
[waitingtime],
[totaltime],
[activetime],
[worktime],
[holdtime],
[transfertime],
[rebootingtime],
[reconnectingtime],
[platform],
[technicianemail],
[techniciangroup],
[browsertype]
)
VALUES (
SOURCE.[sessionid],
SOURCE.[starttime],
SOURCE.[endtime],
SOURCE.[lastactiontime],
SOURCE.[technicianname],
SOURCE.[technicianid],
SOURCE.[sessiontype],
SOURCE.[status],
SOURCE.[contactname],
SOURCE.[companyname],
SOURCE.[email],
SOURCE.[subject],
SOURCE.[existingticketno],
SOURCE.[santander],
SOURCE.[trackingid],
SOURCE.[customerip],
SOURCE.[deviceid],
SOURCE.[toolsused],
SOURCE.[channelid],
SOURCE.[channelname],
SOURCE.[callingcard],
SOURCE.[connectingtime],
SOURCE.[waitingtime],
SOURCE.[totaltime],
SOURCE.[activetime],
SOURCE.[worktime],
SOURCE.[holdtime],
SOURCE.[transfertime],
SOURCE.[rebootingtime],
SOURCE.[reconnectingtime],
SOURCE.[platform],
SOURCE.[technicianemail],
SOURCE.[techniciangroup],
SOURCE.[browsertype]
);
